### ISSUE TITLE
Allow for bags from Aurora that do not have an origin field

### ISSUE THREAD

**Issue by bonniegee** [RockefellerArchiveCenter/ursa_major#113]
Currently, in v1.0 Ursa Major rejects bags that do not have an "origin" field (i.e., sent by Aurora before the "origin" field was added as a feature), because it evaluates them using the accession json schema. The json scheme for Aurora bags should be updated to remove "origin" as a requirement.

**Comment by bonniegee** [comment]
@helrond I implemented this fix and tested with fixtures from the previous version of Ursa Major. However, I also had to modify that "process status" schema to include `75`, as that was the process status of those test bags. Can you advise whether the test needs to be updated, or the process status requirement? See https://github.com/RockefellerArchiveCenter/ursa_major/blob/v1.0/ursa-major-schema.json#L87

**Comment by helrond** [comment]
@bonniegee great! I think the schema needs to be updated to account for additional processing statuses - this feels like an extension of this issue.

When you get around to submitting a PR, let's make sure we have some test fixtures which account for this case (pre-Aurora 2.0 bags).
