### ISSUE TITLE
Delivery view test inconsistently failing in Travis

### ISSUE THREAD

**Issue by bonniegee** [RockefellerArchiveCenter/ursa_major#156]
The bag delivery view test is inconsistently failing in Travis. It only fails when an initial build is started in Travis--such as with a new commit or PR. However, the test passes successfully when the build is restarted. Additionally, the test consistently passes locally.

```
FAIL: test_deliver_view (bagdiscovery.tests.BagTestCase)

Ensures BagDeliveryView executes BagDelivery routine.

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/usr/local/lib/python3.6/unittest/mock.py", line 1183, in patched

    return func(*args, **keywargs)

  File "/code/bagdiscovery/tests.py", line 101, in test_deliver_view

    self.assertEqual(mock_post.call_count, 1)

AssertionError: 2 != 1

```

**Comment by helrond** [comment]
@bonniegee wondering if resetting the mock would work? I'm also seeing that we're patching `bagdiscovery.routines.requests.post` in the `test_deliver_bags` method so you may want to try resetting them both?
