### ISSUE TITLE
Bags (from Zorya) are still in source directory after processing is complete

### ISSUE THREAD

**Issue by bonniegee** [RockefellerArchiveCenter/ursa_major#164]
## Is your feature request related to a problem? Please describe.
On prod, Ursa Major's source directory contains hundreds of TAR files for bags (from Zorya) that were successfully processed. These bags should be removed once they're successfully processed by Ursa Major.

## Describe the solution you'd like
Bags in the source directory should be removed at the end of the Bag Discovery routine.

## Additional context
@helrond , I assume this functionality was not already there because Aurora is already taking care of cleaning these types of files up. In that case, any solution would need to not cause issues with Aurora.

**Comment by helrond** [comment]
I think the issue is in the `move_bag` method of the `BagDiscovery` class - it looks like digitization bags are being copied to the destination directory while all others are being moved. So I think you can delete those bags but then we'll need to fix this in the code as well.

**Comment by bonniegee** [comment]
@helrond Working on this more and I don't think it's in originating in the `move_bag` method--in [line 112](https://github.com/RockefellerArchiveCenter/ursa_major/blob/5f76ad6fb7e99bb69b9ddb9dc69f00ee78cc08c5/bagdiscovery/routines.py#L112), all types of bags are being moved, not copied. Also, this `move_bag` method is dealing with the temporary directory, not the source directory--and bags are being left in the source directory. 

I am having trouble finding this in the Aurora code, but is Aurora deleting bags in Aurora's destination directory (which is Ursa Major's source directory) after it receives the process status update from Aquarius?

**Comment by helrond** [comment]
Yes, it looks like a CleanupRoutine class is executed from the `update` method of the Transfers API Viewset.
